### ISSUE TITLE
Issue with "Fixing our broken program"

### ISSUE THREAD

**Issue by inprogresspleasehold** [learn-co-curriculum/enough-git-for-learn-co#5]
In "Fixing our broken program," the test continues to fail even though the only text in the file is 

puts "Hello World!"

as instructed. I've saved it several times with no change when I run learn from the Learn app terminal.

Any ideas what's going wrong?

![screen shot 2016-07-01 at 5 17 12 pm](https://cloud.githubusercontent.com/assets/18602054/16534683/b59c700c-3faf-11e6-9f9e-97ccbbbc3170.png)

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by pletcher** [comment]
This looks like a syncing issue -- @loganhasson, any clues?

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue is being closed now as stale. If the issue is encountered again, please first consult the [Learn Help Center](http://help.learn.co/) and the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature. If neither of those options resolves the problem and you still feel that this is an issue with the curriculum, please reopen this issue and provide as much detail as possible:
- An expanded explanation of what's going on.
- Steps to reproduce the issue.
- Details about your environment.
  + What's your operating system? Which version?
  + Are you using the Learn IDE or a local development environment?
- A [stack trace](https://en.wikipedia.org/wiki/Stack_trace) of any errors.

Thanks! 🙂
